@startmindmap Mindmap-GetCollateralUnrevealedExpired


<style>
mindmapDiagram {
    node   {
        LineColor black
        Padding 12
        Margin 3
        HorizontalAlignment center
        .mandatory {
            BackgroundColor darkorange
            RoundCorner 60
            MaximumWidth 100
            LineThickness 1
        }
        .opt {
            BackgroundColor orange
            RoundCorner 60
            LineThickness 0
        }
        .datum {
            HorizontalAlignment left
            RoundCorner 0
            BackgroundColor lightgreen
            Padding 3
        }
        .ref {
            HorizontalAlignment left
            RoundCorner 60
            MaximumWidth 100
            LineThickness 1
        }
        .value {
            HorizontalAlignment left
            RoundCorner 0
            BackgroundColor gold
            Padding 3
        }
        .minting {
            HorizontalAlignment left
            RoundCorner 0
            BackgroundColor pink
            Padding 3
        }
    }

    rootNode {
        Padding 30
        Margin 20
        LineColor blue
        BackgroundColor lightgrey
        LineThickness 1.0
        RoundCorner 0
        Shadowing 10.0
    }
}
</style>


title Get Collateral Of Unrevealed Expired Ticket - Transaction
caption  This transaction allows the raffle owner to get the collateral of an unrevealed ticket.


' 🔥
' 🎫
' 🎟️
'🏆
'🔗
' 

*:
TRANSACTION
====
🔥 Burns Ticket Reference NFT 🎟️🔗 
;

left side
**_  **Burn TicketId **
*** 📜Raffle Minting Policy <<minting>>

** Address with\n Ticket Validator\nRef. Script 
***: REF. SCRIPT
====
🧾  Ticket Validator ; <<ref>>



** Raffle Validator \nAddress <<ref>>
***: VALUE
====
🎫🔗 Raffle Reference NFT
💰 Raffle Collateral Value 
🏆 Raffle Stake Value
(₳) Accumulated Value ; <<value>>
***: INLINE DATUM
====
📝 Raffle State Data ; <<datum>>

**_ **RedeemPrize ticketID**
*** Ticket Validator \nAddress <<mandatory>>
****: VALUE
====
🎟️🔗 Ticket Reference NFT
💰 Ticket Collateral Value ; <<value>>
****: INLINE DATUM
====
📝 Ticket State Data ; <<datum>>

** .. <<mandatory>>
***: VALUE
====
🎫👦🏻 Raffle User NFT; <<value>>
** .. <<opt>>
*** .. <<value>>

right side

** ..<<mandatory>>
***: VALUE
====
🎫👦🏻 Raffle User NFT
💰 Ticket Collateral Value ; <<value>>



** .. <<opt>>
*** .. <<value>>






' legend
'  burning 🔥
'  minting 🔨
'  datum  📝
'  ticket user NFT 🎫👦🏻
'  ticket reference NFT 🎫🔗
'  raffle user NFT 🎟️👦🏻
'  raffle reference NFT 🎟️🔗

'🏆💰🧾📜📃
' end legend




@endmindmap
