@startmindmap Mindmap-BuyTicket


<style>
mindmapDiagram {
    node   {
        LineColor black
        Padding 12
        Margin 3
        HorizontalAlignment center
        .mandatory {
            BackgroundColor darkorange
            RoundCorner 60
            MaximumWidth 100
            LineThickness 1
        }
        .opt {
            BackgroundColor orange
            RoundCorner 60
            LineThickness 0
        }
        .datum {
            HorizontalAlignment left
            RoundCorner 0
            BackgroundColor lightgreen
            Padding 3
        }
        .ref {
            HorizontalAlignment left
            RoundCorner 60
            MaximumWidth 100
            LineThickness 1
        }
        .value {
            HorizontalAlignment left
            RoundCorner 0
            BackgroundColor gold
            Padding 3
        }
        .minting {
            HorizontalAlignment left
            RoundCorner 0
            BackgroundColor pink
            Padding 3
        }
    }

    rootNode {
        Padding 30
        Margin 20
        LineColor blue
        BackgroundColor lightgrey
        LineThickness 1.0
        RoundCorner 0
        Shadowing 10.0
    }
}
</style>


title Buy Ticket To Raffle - Transaction
caption  This transaction allows to anyone to buy a ticket for an existing  raffle. \n Some "Accumulated value"  may or may not be locked depeding on the raffle state.

' 🔥
' 🎫
' 🎟️
'🏆
'🔗
' 

*:
TRANSACTION
====
🔨 Minting Ticket Reference NFT 🎟️🔗
🔨 Minting Ticket User NFT 🎟️👦🏻;

left side
**_  **MintTicket TicketId**
*** 📜Raffle Minting Policy <<minting>>
** Address with\n Raffle Validator\nRef. Script 
***: REF. SCRIPT
====
🧾  Raffle Validator ; <<ref>>

**_  **BuyTicket SecretHash**
*** Raffle Validator \nAddress <<mandatory>>
****: VALUE
====
🎫🔗 Raffle Reference NFT
💰 Raffle Collateral Value 
🏆 Raffle Stake Value
<i>(₳) Accumulated Value (optional)</i> ; <<value>>
****: INLINE DATUM
====
📝 Raffle State Data; <<datum>>

** .. <<mandatory>>
***: VALUE
====
💰 (₳) TicketPrice Value
(₳) Ticket Collateral Value ;<<value>>

** .. <<opt>>
*** .. <<value>>

right side

** Raffle Validator \nAddress <<mandatory>>
***: VALUE
====
🎫🔗 Raffle Reference NFT
💰 Raffle Collateral Value 
🏆 Raffle Stake Value
<i>(₳) Accumulated Value  (optional)</i> 
        + (₳) TicketPrice Value; <<value>>
***: INLINE DATUM
====
📝 Raffle State Data 
with updated No. of tickets sold; <<datum>>

** Ticket Validator \nAddress <<mandatory>>
***: VALUE
====
🎟️🔗 Ticket Reference NFT
💰 Ticket Collateral Value ; <<value>>
***: INLINE DATUM
====
📝 Ticket State Data ; <<datum>>

** .. <<mandatory>>
***: VALUE
====
🎟️👦🏻 Ticket User NFT; <<value>>

** .. <<opt>>
*** .. <<value>>





' legend
'  burning 🔥
'  minting 🔨
'  datum  📝
'  ticket user NFT 🎫👦🏻
'  ticket reference NFT 🎫🔗
'  raffle user NFT 🎟️👦🏻
'  raffle reference NFT 🎟️🔗

'🏆💰🧾📜📃
' end legend




@endmindmap
